email-server: "smtp.svc.pivotal.io"
email-from: "ci@spring.io"
email-to: ["jvalkealahti@pivotal.io"]
github-repo: "https://github.com/spring-projects-experimental/vscode-extension-webview-angular.git"
github-repo-raw: "https://raw.githubusercontent.com/spring-projects-experimental/vscode-extension-webview-angular"
artifactory-server: "https://repo.spring.io/"
branch: "master"
build-name: "vscode-extension-webview-angular"
